# Generated by Django 5.0.7 on 2024-07-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resume", models.CharField(max_length=20000)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("processed", models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
