# Generated by Django 5.0.7 on 2024-07-11 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resumeApi", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="resume",
            old_name="resume",
            new_name="description",
        ),
    ]
