# Generated by Django 5.0.7 on 2024-07-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumeApi", "0002_rename_resume_resume_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="cv_url",
            field=models.CharField(default=0, max_length=1024),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="resume",
            name="description",
            field=models.CharField(max_length=1024),
        ),
    ]
