# Generated by Django 5.0.7 on 2024-07-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumeApi", "0003_resume_cv_url_alter_resume_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="file_upload",
            field=models.FileField(default=0, upload_to="uploads"),
            preserve_default=False,
        ),
    ]
