# Generated by Django 5.0.7 on 2024-07-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resumeApi", "0004_resume_file_upload"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="file_upload",
            field=models.FileField(upload_to=""),
        ),
    ]
